# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71f34b5179c555000d0f042fd88cdadff427b176648d121412d16383e3d340c8b9fe4d88a87b7129364dc712ecd06a7980b026ed8119b75c722a588d80ae8c49

test:
  secret_key_base: 01225a10b9cffb1bf48bcdd388753e997b8424111f5320a5ba2af57a09d3a14f145d9a69a312be99eb264a15a89f133742f1f0d3f70e3979f29c4b00e2312d18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
